# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 20:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('traveler', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='user', to='loginReg.User')),
            ],
        ),
    ]
