# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0001_initial'),
        ('thor', '0002_remove_trip_traveler'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='travelers',
            field=models.ManyToManyField(related_name='all_travelers', to='loginReg.User'),
        ),
    ]
